Made display modes public to allow for RTIC shared usage of the display
Finomnis/st7565 pull request #18
Opened 2023-08-15 11:59 UTC by deltronix

Solves issue 17 and adds the DOGL128-6 with external 12V supply 
https://github.com/Finomnis/st7565/issues/17

2023-08-15 22:15 UTC, Finomnis requested changes
Added a couple of nitpicks.

2023-08-15 22:15 UTC, Finomnis commented on src/displays/mod.rs
> +/// Display specification for the DOGL128-6 display
Missing empty line between structs

2023-08-15 22:15 UTC, Finomnis commented on src/driver/mode_graphics.rs
> +    /// Initialize GraphicsMode with a page buffer.
Instead of adding a comment here, it might have to be made `pub(crate)` only. I don't intend to expose `GraphicsMode::new()` to the user.

2023-08-15 22:15 UTC, Finomnis commented on src/driver/mode_initial.rs
> -/// This mode is purely to transition into other modes.
I think I like how the documentation looked previously, so I'd prefer not to delete those two lines. I don't mind the duplication in the docstring of `InitialMode`.

2023-08-15 22:16 UTC, Finomnis commented
Also, would you mind posting a picture of the display in action? Just out of curiousity :)

2023-08-16 10:05 UTC, deltronix commented
I've made the changes as requested, and of course here's the display in action:
![IMG_20230816_120252.jpg](https://github.com/Finomnis/st7565/assets/80849143/576c5ce8-1709-422b-af8c-effa764e95a1)

2023-08-16 22:56 UTC, Finomnis approved these changes

2023-08-16 22:57 UTC, merged

2023-08-19 21:01 UTC, Finomnis commented
@deltronix I just realized that the display specification says `132,64,8`, while the documentation says `128x64`. Is this a typo that needs fixing?

2023-08-20 12:26 UTC, deltronix commented
> * ElectronicVolume. Manual: `0b010000`, your code: `0b010110`
> * VoltageRegulatorResistorValue: Manual: `0b111`, your code: `0b100111` (is equal to `0b111` because only the last three bits count)
> 
> Would you mind testing your display again with those values?

The values I used come from [this datasheet](https://www.lcd-module.com/eng/pdf/grafik/dogl128-6e.pdf). Under the "low voltage" initialization example. The values you suggest are for the "low power" mode (without external contrast power supply).

> @deltronix I just realized that the display specification says `132,64,8`, while the documentation says `128x64`. Is this a typo that needs fixing?
> _EDIT:_ I just read in the manual that the configuration we merged configures the display in 180 degree rotation mode and that the first pixel is at address 4. Is that the reason for the width of 132? If so, we could see if there's a better solution, like introducing a pixel offset parameter. This is the first display that does not span the full 132 pixels, so I wasn't aware of that behavior.

Ah yes the rotation is specific to my pcb design, perhaps there should be a method to "flip" the display as changing this setting doesn't really warrant a whole new "configuration" to be merged.

As for the pixel offset parameter, yes I think that'd be preferable. I think I ran into this issue because in the normal orientation those 4 pixels would be at the end of each page...

2024-05-19 01:13 UTC, agrif commented
I'm using this crate on a mystery 128x64 display inside Quansheng UV-K5 radios, which are driven by some variant of the ST7565. I've also run into this issue where the first column starts at index 4. This can be dealt with by using the cropped() function to resize the screen, but I'd love to see a column offset parameter in the display spec trait.

I've run into some other oddities, but I'll make separate issues for them when (well, if) I can figure out whether this is normal ST7565 behavior or if this radio has a clone IC that's behaving strangely.

2024-05-19 07:55 UTC, Finomnis commented
> I'm using this crate on a mystery 128x64 display inside Quansheng UV-K5 radios, which are driven by some variant of the ST7565. I've also run into this issue where the first column starts at index 4. This can be dealt with by using the cropped() function to resize the screen, but I'd love to see a column offset parameter in the display spec trait.
> 
> I've run into some other oddities, but I'll make separate issues for them when (well, if) I can figure out whether this is normal ST7565 behavior or if this radio has a clone IC that's behaving strangely.

DO you feel confident enough to give it a shot yourself, and create a PR? :)

2024-05-19 20:24 UTC, agrif commented
Absolutely!

2024-05-19 20:48 UTC, Finomnis commented
Would you mind creating an issue for it? This here is a conversation on a closed pull request, I'd rather have it somewhere where it can be tracked better :)